export const players = [
    {
        "player_id": 85062,
        "player_name": "Thiago Motta",
        "firstname": "Thiago",
        "lastname": "Motta",
        "number": null,
        "position": "Midfielder",
        "age": 36,
        "birth_date": "28/08/1982",
        "birth_place": "São Bernardo do Campo",
        "birth_country": "Brazil",
        "nationality": "Italy",
        "height": "187 cm",
        "weight": "83 kg"
    },
    {
        "player_id": 268,
        "player_name": "Isaac Hemans Arday",
        "firstname": "Isaac",
        "lastname": "Hemans Arday",
        "number": null,
        "position": "Midfielder",
        "age": 24,
        "birth_date": "26/12/1996",
        "birth_place": null,
        "birth_country": "France",
        "nationality": "France",
        "height": null,
        "weight": null
    },
    {
        "player_id": 279,
        "player_name": "L. Mbe Soh",
        "firstname": "Loïc",
        "lastname": "Mbe Soh",
        "number": null,
        "position": "Defender",
        "age": 19,
        "birth_date": "13/06/2001",
        "birth_place": "Souza Gare",
        "birth_country": "Cameroon",
        "nationality": "France",
        "height": "186 cm",
        "weight": null
    },
    {
        "player_id": 90593,
        "player_name": "M. Güçlü",
        "firstname": "Metehan",
        "lastname": "Güçlü",
        "number": null,
        "position": "Attacker",
        "age": 21,
        "birth_date": "02/04/1999",
        "birth_place": "Montfermeil",
        "birth_country": "France",
        "nationality": "Turkey",
        "height": "182 cm",
        "weight": null
    },
    {
        "player_id": 254,
        "player_name": "G. Buffon",
        "firstname": "Gianluigi",
        "lastname": "Buffon",
        "number": null,
        "position": "Goalkeeper",
        "age": 42,
        "birth_date": "28/01/1978",
        "birth_place": "Carrara",
        "birth_country": "Italy",
        "nationality": "Italy",
        "height": "192 cm",
        "weight": "92 kg"
    },
    {
        "player_id": 263,
        "player_name": "L. Kurzawa",
        "firstname": "Layvin",
        "lastname": "Kurzawa",
        "number": null,
        "position": "Defender",
        "age": 28,
        "birth_date": "04/09/1992",
        "birth_place": "Fréjus",
        "birth_country": "France",
        "nationality": "France",
        "height": "182 cm",
        "weight": "74 kg"
    },
    {
        "player_id": 260,
        "player_name": "C. Dagba",
        "firstname": "Colin",
        "lastname": "Dagba",
        "number": null,
        "position": "Defender",
        "age": 22,
        "birth_date": "09/09/1998",
        "birth_place": "Béthune",
        "birth_country": "France",
        "nationality": "France",
        "height": "170 cm",
        "weight": "62 kg"
    },
    {
        "player_id": 266,
        "player_name": "Á. Di María",
        "firstname": "Ángel Fabián",
        "lastname": "Di María Hernández",
        "number": null,
        "position": "Midfielder",
        "age": 32,
        "birth_date": "14/02/1988",
        "birth_place": "Rosario",
        "birth_country": "Argentina",
        "nationality": "Argentina",
        "height": "180 cm",
        "weight": "75 kg"
    },
    {
        "player_id": 270,
        "player_name": "S. N&apos;Soki",
        "firstname": "Stanley",
        "lastname": "N'Soki",
        "number": null,
        "position": "Defender",
        "age": 21,
        "birth_date": "09/04/1999",
        "birth_place": "Poissy",
        "birth_country": "France",
        "nationality": "France",
        "height": "178 cm",
        "weight": null
    },
    {
        "player_id": 265,
        "player_name": "Arthur Zagre",
        "firstname": "Arthur",
        "lastname": "Zagre",
        "number": null,
        "position": "Defender",
        "age": 19,
        "birth_date": "04/10/2001",
        "birth_place": null,
        "birth_country": "France",
        "nationality": "France",
        "height": null,
        "weight": null
    },
    {
        "player_id": 90594,
        "player_name": "E. Ebimbe",
        "firstname": "Eric Junior",
        "lastname": "Dina Ebimbe",
        "number": null,
        "position": "Midfielder",
        "age": 20,
        "birth_date": "21/11/2000",
        "birth_place": null,
        "birth_country": "France",
        "nationality": "France",
        "height": null,
        "weight": null
    },
    {
        "player_id": 274,
        "player_name": "E. Cavani",
        "firstname": "Edinson Roberto",
        "lastname": "Cavani Gómez",
        "number": null,
        "position": "Attacker",
        "age": 33,
        "birth_date": "14/02/1987",
        "birth_place": "Salto",
        "birth_country": "Uruguay",
        "nationality": "Uruguay",
        "height": "184 cm",
        "weight": "71 kg"
    },
    {
        "player_id": 253,
        "player_name": "A. Areola",
        "firstname": "Alphonse",
        "lastname": "Areola",
        "number": null,
        "position": "Goalkeeper",
        "age": 27,
        "birth_date": "27/02/1993",
        "birth_place": "Paris",
        "birth_country": "France",
        "nationality": "France",
        "height": "195 cm",
        "weight": "94 kg"
    },
    {
        "player_id": 275,
        "player_name": "Jean-Eric Maxim Choupo-Moting",
        "firstname": "Jean-Eric Maxim",
        "lastname": "Choupo-Moting",
        "number": null,
        "position": "Attacker",
        "age": 31,
        "birth_date": "23/03/1989",
        "birth_place": "Hamburg",
        "birth_country": "Germany",
        "nationality": "Cameroon",
        "height": "191 cm",
        "weight": "82 kg"
    },
    {
        "player_id": 269,
        "player_name": "C. Nkunku",
        "firstname": "Christopher",
        "lastname": "Nkunku",
        "number": null,
        "position": "Midfielder",
        "age": 23,
        "birth_date": "14/11/1997",
        "birth_place": "Lagny-sur-Marne",
        "birth_country": "France",
        "nationality": "France",
        "height": "178 cm",
        "weight": "68 kg"
    },
    {
        "player_id": 277,
        "player_name": "M. Diaby",
        "firstname": "Moussa",
        "lastname": "Diaby",
        "number": null,
        "position": "Attacker",
        "age": 21,
        "birth_date": "07/07/1999",
        "birth_place": "Paris",
        "birth_country": "France",
        "nationality": "France",
        "height": "170 cm",
        "weight": "65 kg"
    },
    {
        "player_id": 257,
        "player_name": "Marcos  Aoás Corrêa",
        "firstname": "Marcos",
        "lastname": "Aoás Corrêa",
        "number": null,
        "position": "Defender",
        "age": 26,
        "birth_date": "14/05/1994",
        "birth_place": "São Paulo",
        "birth_country": "Brazil",
        "nationality": "Brazil",
        "height": "183 cm",
        "weight": "75 kg"
    },
    {
        "player_id": 259,
        "player_name": "Thiago Emiliano da Silva",
        "firstname": "Thiago Emiliano",
        "lastname": "da Silva",
        "number": null,
        "position": "Defender",
        "age": 36,
        "birth_date": "22/09/1984",
        "birth_place": "Rio de Janeiro",
        "birth_country": "Brazil",
        "nationality": "Brazil",
        "height": "183 cm",
        "weight": "79 kg"
    },
    {
        "player_id": 276,
        "player_name": "Neymar",
        "firstname": "Neymar",
        "lastname": "da Silva Santos Júnior",
        "number": null,
        "position": "Attacker",
        "age": 28,
        "birth_date": "05/02/1992",
        "birth_place": "Mogi das Cruzes",
        "birth_country": "Brazil",
        "nationality": "Brazil",
        "height": "175 cm",
        "weight": "68 kg"
    },
    {
        "player_id": 1578,
        "player_name": "Giovani Lo Celso",
        "firstname": "Giovani",
        "lastname": "Lo Celso",
        "number": null,
        "position": "Midfielder",
        "age": 24,
        "birth_date": "09/04/1996",
        "birth_place": "Rosario",
        "birth_country": "Argentina",
        "nationality": "Argentina",
        "height": "177 cm",
        "weight": "68 kg"
    },
    {
        "player_id": 271,
        "player_name": "Leandro Daniel Paredes",
        "firstname": "Leandro Daniel",
        "lastname": "Paredes",
        "number": null,
        "position": "Midfielder",
        "age": 26,
        "birth_date": "29/06/1994",
        "birth_place": "San Justo",
        "birth_country": "Argentina",
        "nationality": "Argentina",
        "height": "180 cm",
        "weight": "75 kg"
    },
    {
        "player_id": 273,
        "player_name": "Marco Verratti",
        "firstname": "Marco",
        "lastname": "Verratti",
        "number": null,
        "position": "Midfielder",
        "age": 28,
        "birth_date": "05/11/1992",
        "birth_place": "Pescara",
        "birth_country": "Italy",
        "nationality": "Italy",
        "height": "165 cm",
        "weight": "60 kg"
    },
    {
        "player_id": 267,
        "player_name": "Julian Draxler",
        "firstname": "Julian",
        "lastname": "Draxler",
        "number": null,
        "position": "Midfielder",
        "age": 27,
        "birth_date": "20/09/1993",
        "birth_place": "Gladbeck",
        "birth_country": "Germany",
        "nationality": "Germany",
        "height": "185 cm",
        "weight": "72 kg"
    },
    {
        "player_id": 1090,
        "player_name": "Antoine Joseph Emmanuel Bernède",
        "firstname": "Antoine Joseph Emmanuel",
        "lastname": "Bernède",
        "number": null,
        "position": "Midfielder",
        "age": 21,
        "birth_date": "26/05/1999",
        "birth_place": "Paris",
        "birth_country": "France",
        "nationality": "France",
        "height": "177 cm",
        "weight": "74 kg"
    },
    {
        "player_id": 90591,
        "player_name": "Azzeddine Toufiqui",
        "firstname": "Azzeddine",
        "lastname": "Toufiqui",
        "number": null,
        "position": "Midfielder",
        "age": 21,
        "birth_date": "25/04/1999",
        "birth_place": "Caen",
        "birth_country": "France",
        "nationality": "France",
        "height": "175 cm",
        "weight": null
    },
    {
        "player_id": 14474,
        "player_name": "Kévin Ramon Rimane",
        "firstname": "Kévin Ramon",
        "lastname": "Rimane",
        "number": null,
        "position": "Defender",
        "age": 29,
        "birth_date": "23/02/1991",
        "birth_place": "Cayenne",
        "birth_country": "French Guiana",
        "nationality": "French Guiana",
        "height": "181 cm",
        "weight": "74 kg"
    },
    {
        "player_id": 261,
        "player_name": "Thilo Kehrer",
        "firstname": "Thilo",
        "lastname": "Kehrer",
        "number": null,
        "position": "Defender",
        "age": 24,
        "birth_date": "21/09/1996",
        "birth_place": "Tübingen",
        "birth_country": "Germany",
        "nationality": "Germany",
        "height": "186 cm",
        "weight": "76 kg"
    },
    {
        "player_id": 255,
        "player_name": "Sébastien Cibois",
        "firstname": "Sébastien",
        "lastname": "Cibois",
        "number": null,
        "position": "Goalkeeper",
        "age": 22,
        "birth_date": "02/03/1998",
        "birth_place": "Argenteuil",
        "birth_country": "France",
        "nationality": "France",
        "height": "178 cm",
        "weight": null
    },
    {
        "player_id": 1800,
        "player_name": "K. Trapp",
        "firstname": "Kevin",
        "lastname": "Trapp",
        "number": null,
        "position": "Goalkeeper",
        "age": 30,
        "birth_date": "08/07/1990",
        "birth_place": "Merzig",
        "birth_country": "Germany",
        "nationality": "Germany",
        "height": "189 cm",
        "weight": "88 kg"
    },
    {
        "player_id": 264,
        "player_name": "T. Meunier",
        "firstname": "Thomas",
        "lastname": "Meunier",
        "number": null,
        "position": "Midfielder",
        "age": 29,
        "birth_date": "12/09/1991",
        "birth_place": "Sainte-Ode",
        "birth_country": "Belgium",
        "nationality": "Belgium",
        "height": "190 cm",
        "weight": "82 kg"
    },
    {
        "player_id": 262,
        "player_name": "P. Kimpembe",
        "firstname": "Presnel",
        "lastname": "Kimpembe",
        "number": null,
        "position": "Defender",
        "age": 25,
        "birth_date": "13/08/1995",
        "birth_place": "Beaumont-sur-Oise",
        "birth_country": "France",
        "nationality": "France",
        "height": "183 cm",
        "weight": "77 kg"
    },
    {
        "player_id": 278,
        "player_name": "K. Mbappé",
        "firstname": "Kylian",
        "lastname": "Mbappé Lottin",
        "number": null,
        "position": "Attacker",
        "age": 22,
        "birth_date": "20/12/1998",
        "birth_place": "Paris",
        "birth_country": "France",
        "nationality": "France",
        "height": "178 cm",
        "weight": "73 kg"
    },
    {
        "player_id": 272,
        "player_name": "A. Rabiot",
        "firstname": "Adrien",
        "lastname": "Rabiot",
        "number": null,
        "position": "Midfielder",
        "age": 25,
        "birth_date": "03/04/1995",
        "birth_place": "Saint-Maurice",
        "birth_country": "France",
        "nationality": "France",
        "height": "188 cm",
        "weight": "71 kg"
    },
    {
        "player_id": 258,
        "player_name": "Juan Bernat",
        "firstname": "Juan",
        "lastname": "Bernat Velasco",
        "number": null,
        "position": "Defender",
        "age": 27,
        "birth_date": "01/03/1993",
        "birth_place": "Valencia",
        "birth_country": "Spain",
        "nationality": "Spain",
        "height": "177 cm",
        "weight": "67 kg"
    },
    {
        "player_id": 1585,
        "player_name": "Jesé",
        "firstname": "Jesé",
        "lastname": "Rodríguez Ruiz",
        "number": null,
        "position": "Attacker",
        "age": 27,
        "birth_date": "26/02/1993",
        "birth_place": "Las Palmas de Gran Canaria",
        "birth_country": "Spain",
        "nationality": "Spain",
        "height": "178 cm",
        "weight": "72 kg"
    },
    {
        "player_id": 256,
        "player_name": "Daniel Alves da Silva",
        "firstname": "Daniel",
        "lastname": "Alves da Silva",
        "number": null,
        "position": "Midfielder",
        "age": 37,
        "birth_date": "06/05/1983",
        "birth_place": "Juazeiro",
        "birth_country": "Brazil",
        "nationality": "Brazil",
        "height": "172 cm",
        "weight": "70 kg"
    },
    {
        "player_id": 1138,
        "player_name": "T. Weah",
        "firstname": "Timothy",
        "lastname": "Weah",
        "number": null,
        "position": "Attacker",
        "age": 20,
        "birth_date": "22/02/2000",
        "birth_place": "New York",
        "birth_country": "USA",
        "nationality": "USA",
        "height": "183 cm",
        "weight": "66 kg"
    }
]